post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "zhenka",
    "password": "salainen"
}

###
post http://localhost:3001/api/users
Content-Type: application/json

{
	        "username": "zhenka",
			"name": "Superuser",
			"password": "salainen"

}


###
GET http://localhost:3000/api/photos
Content-Type: application/json
Authorization: 563492ad6f91700001000001a8d6b5c41c804b8196922cb3672d53d0


{
	        "content": "bbbbsss",
            "important": true

}

###
get http://localhost:3001/api/notes/


###
DELETE http://localhost:3001/api/notes/630640c0db0bb118c31171de

###
PUT http://localhost:3001/api/notes/63086185dee04c2fbe7362b0
